apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-03-5c5c3b4d47f2/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
